### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Couldn't parse config file: unknown field `language`, expected one of `header`, `includes`, `imports`, `trailer`, `no_includes`, `autogen_warning`, `include_version`, `line_length`, `tab_width`, `parse`, `export`, `macro_expansion`, `layout`, `fn`, `struct`, `enum`, `const`, `defines`, `documentation`, `documentation_style` at line 129 column 1."', /Users/z/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/nbindgen-0.0.1/src/main.rs:63:41

### ISSUE THREAD

**Issue by eyun-tv** [arnetheduck/nbindgen#1]
❯ nbindgen --config nbindgen.toml --crate roaring --output lib.h
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Couldn't parse config file: unknown field `language`, expected one of `header`, `includes`, `imports`, `trailer`, `no_includes`, `autogen_warning`, `include_version`, `line_length`, `tab_width`, `parse`, `export`, `macro_expansion`, `layout`, `fn`, `struct`, `enum`, `const`, `defines`, `documentation`, `documentation_style` at line 129 column 1."', /Users/z/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/nbindgen-0.0.1/src/main.rs:63:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by arnetheduck** [comment]
The `.toml` file you supplied is not valid for `nbindgen` (it does not understand the `language` option - you need to remove any such `cbindgen` options
